name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
	os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Install alsaudio
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libasound2-dev libxrandr-dev

    - name: Configure CMake
      run: cmake -S . -B build/

    - name: Build
      run: cmake --build build/ --parallel $(nproc)
