name: Build and Test

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev cmake build-essential

    - name: Configure CMake
      run: cmake -S . -B build/

    - name: Build
      run: cmake --build build/ --parallel $(nproc)
