name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && apt-get install -y libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev cmake build-essential

    - name: Configure CMake
      run: cmake -S . -B build/

    - name: Build
      run: cmake --build build/ --parallel $(nproc)
